name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest

jobs:
  node-matrix:
    strategy:
      matrix:
        os: ["${{ inputs.os }}"]
        node-version: [14, 15, 16]
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
