name: Matrix
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        node-version: [14, 15, 16]
        nodes-os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.nodes-os }}
    steps:
      - run: node -v
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
