name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 15, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          # excludes node 14, 15 on macOS
          - os: macos-latest
            node-version: "toJson('[14, 15]')"

    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - name: setup node
        uses: actions/setup-node@v3
      - run: node -v
