name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 15, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ (runner.os == 'macOS' && runner.arch == 'ARM64') && 'arm64' || 'x64' }}

      - run: node -v
