name: Working Dirs & Shells
on: [push]
defaults:
  run:
    shell: bash
    # working-directory: /de/ed
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd 
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working directory
        working-directory: /home/runner
        run: pwd

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files on windows
        shell: pwsh
        run: |
          pwd 
          Get-Location
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Run Python in Windows
        shell: python
        run: |
          import platform
          print(platform.processor())
